; php.ini или отдельный файл, например /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

zend_extension=xdebug.so

[xdebug]
xdebug.mode=debug
xdebug.start_with_request=yes

; указываем куда слать соединения (IDE)
; Внутри Docker под WSL2 "host.docker.internal" работает начиная с Docker Desktop 18.03+
xdebug.client_host=host.docker.internal

; Порт, который слушает IDE (обычно 9003 в Xdebug 3)
xdebug.client_port=9003

; Дополнительно для удобства
xdebug.log=/tmp/xdebug.log
xdebug.discover_client_host=false
