<?php

namespace App\Jobs;

use App\Common\DTO\DifferenceDataDTO;
use App\Interfaces\ContentGenerator\DiffGeneratorInterface;
use App\Models\PageVersion;
use App\Models\VersionDiffTask;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;

class CalculateVersionDifferenceJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    /**
     * The number of times the job may be attempted.
     *
     * @var int
     */
    public $tries = 3;

    /**
     * Create a new job instance.
     */
    public function __construct(
        public int $newVersionId,
        public ?int $oldVersionId = null
    ) {}

    /**
     * Execute the job.
     */
    public function handle(DiffGeneratorInterface $diffGenerator): void
    {
        $newVersion = PageVersion::findOrFail($this->newVersionId);

        // Create chat and VersionDiffTask record
        $chat = \App\Models\LLMChat::create(['messages' => []]);

        $versionDiffTask = VersionDiffTask::create([
            'project_id' => $newVersion->page->project_id,
            'page_version_id' => null,
            'content' => null,  // Will be generated by GenerateTaskDescriptionJob
            'created_by' => $newVersion->page->created_by,
            'generation_status' => VersionDiffTask::STATUS_PENDING,
            'llm_chat_id' => $chat->id,
        ]);

        // Attach the page version via pivot table
        $versionDiffTask->pageVersions()->syncWithoutDetaching([$newVersion->id]);

        // Dispatch the next job in the chain with the ID
        GenerateTaskDescriptionJob::dispatch($versionDiffTask->id);
    }
}
