<?php

namespace App\Jobs;

use App\Common\DTO\DifferenceDataDTO;
use App\Interfaces\ContentGenerator\DiffGeneratorInterface;
use App\Models\PageVersion;
use App\Models\VersionDiffTask;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;

class CalculateVersionDifferenceJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    /**
     * The number of times the job may be attempted.
     *
     * @var int
     */
    public $tries = 3;

    /**
     * Create a new job instance.
     */
    public function __construct(
        public int $newVersionId,
        public ?int $oldVersionId = null
    ) {}

    /**
     * Execute the job.
     */
    public function handle(DiffGeneratorInterface $diffGenerator): void
    {
        $newVersion = PageVersion::findOrFail($this->newVersionId);
        $oldVersion = $this->oldVersionId ? PageVersion::find($this->oldVersionId) : null;

        // Create chat and VersionDiffTask record
        $chat = \App\Models\LLMChat::create(['messages' => []]);

        $versionDiffTask = VersionDiffTask::create([
            'project_id' => $newVersion->page->project_id,
            'page_version_id' => $newVersion->id,
            'content' => null,  // Will be generated by GenerateTaskDescriptionJob
            'created_by' => $newVersion->page->created_by,
            'generation_status' => VersionDiffTask::STATUS_PENDING,
            'llm_chat_id' => $chat->id,
        ]);

        // Dispatch the next job in the chain with the ID
        GenerateTaskDescriptionJob::dispatch($versionDiffTask->id);
    }

    /**
     * Calculate difference between two versions
     */
    private function calculateDifference(PageVersion $newVersion, ?PageVersion $oldVersion, DiffGeneratorInterface $diffGenerator): DifferenceDataDTO
    {
        $isNewPage = $oldVersion === null;
        $titleChanged = false;
        $contentChanged = false;
        $diffOutput = '';

        if ($oldVersion) {
            $titleChanged = $newVersion->title !== $oldVersion->title;
            $contentChanged = $newVersion->content !== $oldVersion->content;

            // Generate diff output in git diff format
            $diffOutput = $diffGenerator->generateDiff($oldVersion->content, $newVersion->content);
            if ($titleChanged) {
                $diffOutput = $diffGenerator->generateDiff($oldVersion->title, $newVersion->title, 'title') . "\n" . $diffOutput;
            }
        } else {
            // For new pages, show all content as added
            $diffOutput = $diffGenerator->generateDiff('', $newVersion->content);
            if (!empty($newVersion->title)) {
                $diffOutput = $diffGenerator->generateDiff('', $newVersion->title, 'title') . "\n" . $diffOutput;
            }
        }

        return new DifferenceDataDTO(
            diffOutput: $diffOutput,
            newVersionTitle: $newVersion->title,
            isNewPage: $isNewPage,
            titleChanged: $titleChanged,
            contentChanged: $contentChanged
        );
    }
}
